### ISSUE TITLE
致谢

### ISSUE THREAD

**Issue by kongdd** [PanfengZhang/adw#1]
感谢开源这个R包。
这个R包写的非常好，学习到很多。rrodrigojrr的这个版本<https://github.com/rrodrigojrr/ADW>，虽然文章引用次数很高，但代码里很有错误。

希望以后有机会合作。
> 孔冬冬

**Comment by kongdd** [comment]
## 一些扩展建议
1. 对于时间序列数据，如常用的站点数据, [nsite, ntime]，假设不考虑站点变更，这样权重算一次即可；
2. 弃用sf，这样在计算权重的时候速度可能会提高60倍左右

**Comment by PanfengZhang** [comment]
谢谢孔老师认可，目前这个包已经在CRAN（https://CRAN.R-project.org/package=adw）上发布，但是还存在一些问题：


1.在针对全球的计算时，不同的纬度带需要使用不同的插值半径，这个包未来可能还需要添加一些新的函数以满足不同需求。
2.目前这个包的计算速度异常的慢。仅仅一片小区域就花费很多时间。


如果您有兴趣，未来我们可以合作改进这个包。您写的R包rcolors，我平时也在使用，解决了R用户使用NCL配色方案的一个痛点。

张盼峰


发件人：Dongdong Kong ***@***.***>
发送日期：2022-04-19 16:21:07
收件人：PanfengZhang/adw ***@***.***>
抄送人：Subscribed ***@***.***>
主题：Re: [PanfengZhang/adw] 致谢 (Issue #1)

一些扩展建议对于时间序列数据，如常用的站点数据, [nsite, ntime]，假设不考虑站点变更，这样权重算一次即可； 弃用sf，这样在计算权重的时候速度可能会提高60倍左右—

**Comment by PanfengZhang** [comment]
好的，谢谢。
构建sf对象的目的是为了以网格中心为圆心、以插值半径为圆半径构建一个圆（sf对象的圆，相当于多边形），然后用这个sf对象的圆来寻找哪些台站落在这个圆里面。如果没有这个sf对象的圆的话，我可能得计算网格中心与所有台站的距离，然后再筛选符合距离条件台站进行插值。







发件人：Dongdong Kong ***@***.***>
发送日期：2022-04-19 16:21:07
收件人：PanfengZhang/adw ***@***.***>
抄送人：Subscribed ***@***.***>
主题：Re: [PanfengZhang/adw] 致谢 (Issue #1)

一些扩展建议对于时间序列数据，如常用的站点数据, [nsite, ntime]，假设不考虑站点变更，这样权重算一次即可； 弃用sf，这样在计算权重的时候速度可能会提高60倍左右—

**Comment by kongdd** [comment]
一个简易的方法可以实现同样的功能。精度有微弱的受损（估计误差在1%左右），但影响不大，二者空间分布的图基本一致、肉眼难以分辨：
> 半径可以转化为度，然后以网格为中心，框一个正方形，落在正方形区域的站点才计算距离。

![image](https://user-images.githubusercontent.com/9815742/163971239-cc72beb2-1cff-4f9e-83a1-84bca13eca35.png)

**Comment by PanfengZhang** [comment]
好的，这个方法好，非常感谢。






发件人：Dongdong Kong ***@***.***>
发送日期：2022-04-19 17:15:10
收件人：PanfengZhang/adw ***@***.***>
抄送人：Panfeng Zhang ***@***.***>,Comment ***@***.***>
主题：Re: [PanfengZhang/adw] 致谢 (Issue #1)

一个简易的方法可以实现同样的功能。精度有微弱的受损（估计误差在1%左右），但影响不大，二者空间分布的图基本一致、肉眼难以分辨：
半径可以转化为度，然后以网格为中心，框一个正方形，落在正方形区域的站点才计算距离。
